mdapi_output_dir/objects/DailyReport__c.object
<CustomObject>
    <label>日報</label>
    <nameField>
        <displayFormat>日報No{0000}</displayFormat>
        <label>日報No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>BreakTime__c</fullName>
        <label>休憩時間（分）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DailyReportType__c</fullName>
        <label>日報種別</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>出勤</fullName>
                </value>
                <value>
                    <fullName>休日</fullName>
                </value>
                <value>
                    <fullName>有休</fullName>
                </value>
                <value>
                    <fullName>代休</fullName>
                </value>
                <value>
                    <fullName>欠勤</fullName>
                </value>
                <value>
                    <fullName>特休</fullName>
                </value>
                <value>
                    <fullName>休日出勤</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MasterMemberId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>関連メンバー</label>
        <referenceTo>MasterMember__c</referenceTo>
        <relationshipLabel>日報</relationshipLabel>
        <relationshipName>DailyReports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MidnightTime__c</fullName>
        <label>深夜時間（分）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MonthlyReportId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>関連勤怠</label>
        <referenceTo>MonthlyReport__c</referenceTo>
        <relationshipLabel>日報</relationshipLabel>
        <relationshipName>DailyReports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OverTime__c</fullName>
        <label>時間外（分）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PaidTime__c</fullName>
        <label>有休時間（分）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WorkTime__c</fullName>
        <label>労働時間（分）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

mdapi_output_dir/objects/MasterMember__c.object
<CustomObject>
    <label>メンバーマスタ</label>
    <nameField>
        <label>名前</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>FixedOvertime__c</fullName>
        <label>固定残業時間</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>関連ユーザ</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>メンバーマスタ</relationshipLabel>
        <relationshipName>MasterMember</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapi_output_dir/objects/MonthlyReport__c.object
<CustomObject>
    <label>勤怠</label>
    <nameField>
        <label>勤怠</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>MasterMemberId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>関連メンバー</label>
        <referenceTo>MasterMember__c</referenceTo>
        <relationshipLabel>勤怠</relationshipLabel>
        <relationshipName>MonthlyReports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalaryMonth__c</fullName>
        <label>給与月</label>
        <type>Date</type>
    </fields>
</CustomObject>

mdapi_output_dir/objects/PaidHolidays__c.object
<CustomObject>
    <label>有給休暇</label>
    <nameField>
        <displayFormat>有給休暇No{0000}</displayFormat>
        <label>有給休暇No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>CarryForwardDays__c</fullName>
        <label>繰越残（日数）</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CarryForwardTime__c</fullName>
        <label>繰越残（時間）</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GrantDate__c</fullName>
        <label>付与年月日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GrantDays__c</fullName>
        <label>付与日数</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MasterMemberId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>関連メンバー</label>
        <referenceTo>MasterMember__c</referenceTo>
        <relationshipLabel>有給休暇</relationshipLabel>
        <relationshipName>PaidHolidays</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>年度（期）</label>
        <length>4</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi_output_dir/classes/MonthlyReportControllerTest.cls
@isTest
public with sharing class MonthlyReportControllerTest {
    
    @isTest static void test_MonthlyReportController() {
        // 現在のユーザIDを設定
        String USRID = UserInfo.getUserId();

        // 本日を設定
        Date TDY11 = Date.today();        

        // テストデータ作成
        // メンバーデータ
        MasterMember__c InsMnb = new MasterMember__c(
            Name = 'テストメンバー',
            FixedOvertime__c = 20,
            UserId__c = USRID
        );
        insert InsMnb;
        
	    // 勤怠テストデータ
        MonthlyReport__c  InsPtm = new MonthlyReport__c (
            Name = '先月の給与',
            SalaryMonth__c = TDY11,
            MasterMemberId__c = InsMnb.Id,
            OwnerId = USRID
        );
        insert InsPtm;

	    // 有給休暇テストデータ
        PaidHolidays__c  InsPhd = new PaidHolidays__c (
            Period__c = '2019',
            GrantDate__c = TDY11,
            MasterMemberId__c = InsMnb.Id,
            GrantDays__c = 10,
            CarryForwardDays__c = 2,
            CarryForwardTime__c = 2,
            OwnerId = USRID
        );
        insert InsPhd;

	    // 日報テストデータ(本日)
        DailyReport__c InsDrt = new DailyReport__c(
            Date__c = TDY11,
            DailyReportType__c = '出勤',
            MasterMemberId__c = InsMnb.Id,
            WorkTime__c = 600,
            BreakTime__c = 60,
            OverTime__c = 60,
			PaidTime__c  = 60,
			MidnightTime__c = 60,
            MonthlyReportId__c = InsPtm.Id,
            OwnerId = USRID
        );
        insert InsDrt;

        DailyReport__c InsDrt2 = new DailyReport__c(
            Date__c = TDY11+1,
            DailyReportType__c = '出勤',
            MasterMemberId__c = InsMnb.Id,
            WorkTime__c = 600,
            BreakTime__c = 60,
            OverTime__c = 60,
			PaidTime__c  = 60,
			MidnightTime__c = 60,
            OwnerId = USRID
        );
        insert InsDrt2;

        DailyReport__c InsDrt3 = new DailyReport__c(
            Date__c = TDY11+2,
            DailyReportType__c = '休日',
            MasterMemberId__c = InsMnb.Id,
            OwnerId = USRID
        );
        insert InsDrt3;

        DailyReport__c InsDrt4 = new DailyReport__c(
            Date__c = TDY11+3,
            DailyReportType__c = '休日出勤',
            MasterMemberId__c = InsMnb.Id,
            WorkTime__c = 600,
            BreakTime__c = 60,
            OverTime__c = 60,
			PaidTime__c  = 60,
			MidnightTime__c = 60,
            OwnerId = USRID
        );
        insert InsDrt4;
        
        
        // テスト開始        
        Test.startTest();

        String result = null;
        result = MonthlyReportController.MonthlyReportAccounting( InsPtm.Id );
        result = MonthlyReportController.MonthlyReportAccounting( InsMnb.Id );

        Test.stopTest();
        
    }

}