mdapi_output_dir/objects/DailyReport__c.object
<CustomObject>
    <label>日報</label>
    <nameField>
        <displayFormat>日報No{0000}</displayFormat>
        <label>日報No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>DailyReportIdentificationId__c</fullName>
        <formula>TEXT(Date__c) + CASESAFEID(MasterMemberId__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>[システム]日報識別ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DailyReportType__c</fullName>
        <label>日報種別</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>出勤</fullName>
                </value>
                <value>
                    <fullName>休日</fullName>
                </value>
                <value>
                    <fullName>有休</fullName>
                </value>
                <value>
                    <fullName>代休</fullName>
                </value>
                <value>
                    <fullName>欠勤</fullName>
                </value>
                <value>
                    <fullName>特休</fullName>
                </value>
                <value>
                    <fullName>休日出勤</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi_output_dir/objects/MasterMember__c.object
<CustomObject>
    <label>メンバーマスタ</label>
    <nameField>
        <label>名前</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Affiliation__c</fullName>
        <label>所属部署</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>営業部</fullName>
                </value>
                <value>
                    <fullName>技術部</fullName>
                </value>
                <value>
                    <fullName>総務部</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EmploymentState__c</fullName>
        <label>雇用状況</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>在職</fullName>
                </value>
                <value>
                    <fullName>休職</fullName>
                </value>
                <value>
                    <fullName>退職</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SortNumber__c</fullName>
        <label>並び順</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WorkingStatus__c</fullName>
        <label>[システム]作業状況</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>休憩中</fullName>
                </value>
                <value>
                    <fullName>外出中</fullName>
                </value>
                <value>
                    <fullName>移動中</fullName>
                </value>
                <value>
                    <fullName>作業中</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/AttendanceController.cls
public with sharing class AttendanceController {

    // メンバーの出勤状況を取得
  @AuraEnabled
    public static void AttendanceStatus() {

        // 配列の定義
//        Data[] datas = New Data[3];

    // 各項目の定義
        String Affiliation = null;
        String MemberName = null;
        String WorkingStatus = null;

        // 有効なメンバーを取得
        List<MasterMember__c> MasterMemberList = [SELECT Id, Name, Affiliation__c, WorkingStatus__c 
                                                                    FROM MasterMember__c  
                                                      WHERE EmploymentState__c = '在職'
                                                      ORDER BY Affiliation__c,SortNumber__c ASC];
//System.debug('MasterMemberList.size　'+MasterMemberList.size());
        // 取得数分繰り返し
      for(integer i=0; MasterMemberList.size()>i; i++){
      // レコード取得
            MasterMember__c  MasterMember = MasterMemberList.get(i);
            // メンバーIDを設定
            ID MasterMemberId = MasterMember.Id;
            
            // 各ステータスを設定
            // 所属部署
            Affiliation = MasterMember.Affiliation__c;
            // 名前
            MemberName = MasterMember.name;
            // 所属部署
            WorkingStatus = MasterMember.WorkingStatus__c;
        

            // 日報識別IDを設定(日付＋関連メンバー)
      String DailyReportIdentificationId = String.valueOf(Date.today()).left(10) + MasterMemberId;

          // 日報を取得
          List<DailyReport__c> DailyReportList = [SELECT Id, DailyReportType__c  
                                                                            FROM DailyReport__c  
                                                              WHERE DailyReportIdentificationId__c = :DailyReportIdentificationId];

          String DailyReportType = null;
            if(DailyReportList.size() > 0){
        // レコード取得
              DailyReport__c  DailyReport = DailyReportList.get(0);
                // 日報種別を設定
                DailyReportType = DailyReport.DailyReportType__c;
            }

System.debug('Affiliation　'+Affiliation);
System.debug('MemberName　'+MemberName);
System.debug('WorkingStatus　'+WorkingStatus);
System.debug('DailyReportType　'+DailyReportType);
//System.debug('datas[i]　'+datas[i]);

        }
    }
}