mdapi_output_dir/objects/DailyReport__c.object
<CustomObject>
    <label>日報</label>
    <nameField>
        <displayFormat>日報No{0000}</displayFormat>
        <label>日報No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>ActualTime__c</fullName>
        <formula>IF( ISPICKVAL(DailyReportType__c, &quot;出勤&quot;),
(( WorkTime__c / 15 ) /4),
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>日報種別が「出勤」なら労働時間（分）から算出
日報種別が「出勤」以外は0</inlineHelpText>
        <label>実労働時間</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AttendanceTimeSelection__c</fullName>
        <label>出勤時間（入力）</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TimeList30</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>AttendanceTime__c</fullName>
        <label>出勤時間</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>BreakTimeSelection__c</fullName>
        <label>休憩時間（入力）</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>0.5</fullName>
                </value>
                <value>
                    <fullName>1.0</fullName>
                    <default>true</default>
                    <label>1.0</label>
                </value>
                <value>
                    <fullName>1.5</fullName>
                </value>
                <value>
                    <fullName>2.0</fullName>
                </value>
                <value>
                    <fullName>2.5</fullName>
                </value>
                <value>
                    <fullName>3.0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DailyReportType__c</fullName>
        <label>日報種別</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>出勤</fullName>
                </value>
                <value>
                    <fullName>休日</fullName>
                </value>
                <value>
                    <fullName>有休</fullName>
                </value>
                <value>
                    <fullName>代休</fullName>
                </value>
                <value>
                    <fullName>欠勤</fullName>
                </value>
                <value>
                    <fullName>特休</fullName>
                </value>
                <value>
                    <fullName>休日出勤</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DisplayTimeStampAttendanceTime__c</fullName>
        <formula>IF( ISBLANK(TimeStampAttendanceTime__c),
&quot;&quot;,
MID( TEXT( TimeStampAttendanceTime__c + 0.375 ),0, 10 )
+
&quot;　&quot;
+
MID( TEXT( TimeStampAttendanceTime__c + 0.375 ), 12, 8)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>[表示用]出勤タイムスタンプ</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DisplayTimeStampLeavingTime__c</fullName>
        <formula>IF( ISBLANK(TimeStampLeavingTime__c),
&quot;&quot;,
MID( TEXT( TimeStampLeavingTime__c + 0.375 ),0, 10 )
+
&quot;　&quot;
+
MID( TEXT( TimeStampLeavingTime__c + 0.375 ), 12, 8)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>[表示用]退勤タイムスタンプ</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HolidayWorkTime__c</fullName>
        <formula>IF( ISPICKVAL(DailyReportType__c, &quot;休日出勤&quot;),
(( WorkTime__c / 15 ) /4),
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>休日出勤時間</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LeavingTimeSelection__c</fullName>
        <label>退勤時間（入力）</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TimeList30Next</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LeavingTime__c</fullName>
        <label>退勤時間</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MasterMemberId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>関連メンバー</label>
        <referenceTo>MasterMember__c</referenceTo>
        <relationshipLabel>日報</relationshipLabel>
        <relationshipName>DailyReports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MidnightTimeHour__c</fullName>
        <formula>IF( OR( ISPICKVAL(DailyReportType__c, &quot;出勤&quot;) , ISPICKVAL(DailyReportType__c, &quot;休日出勤&quot;) ),
(( MidnightTime__c / 15 ) /4),
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>深夜時間</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OverTimeHour__c</fullName>
        <formula>IF( ISPICKVAL(DailyReportType__c, &quot;出勤&quot;),
(( OverTime__c / 30 ) /2),
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>日報種別が「出勤」以外なら0
それ以外は実労働時間が日報_勤務時間を超えた時間を算出</inlineHelpText>
        <label>時間外</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ScheduledAttendanceTime__c</fullName>
        <label>予定出勤時間</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TimeList30</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ScheduledLeavingTime__c</fullName>
        <label>予定退勤時間</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TimeList30Next</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

mdapi_output_dir/objects/MasterMember__c.object
<CustomObject>
    <label>メンバーマスタ</label>
    <nameField>
        <label>名前</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Affiliation__c</fullName>
        <label>所属部署</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>営業部</fullName>
                </value>
                <value>
                    <fullName>技術部</fullName>
                </value>
                <value>
                    <fullName>総務部</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ArrivalStatus__c</fullName>
        <defaultValue>false</defaultValue>
        <label>[システム]出勤状況</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EmploymentState__c</fullName>
        <label>雇用状況</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>在職</fullName>
                </value>
                <value>
                    <fullName>休職</fullName>
                </value>
                <value>
                    <fullName>退職</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RegularTimeEnd__c</fullName>
        <label>定時終了</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>16:00</fullName>
                </value>
                <value>
                    <fullName>16:30</fullName>
                </value>
                <value>
                    <fullName>17:00</fullName>
                </value>
                <value>
                    <fullName>17:30</fullName>
                </value>
                <value>
                    <fullName>18:00</fullName>
                </value>
                <value>
                    <fullName>18:30</fullName>
                </value>
                <value>
                    <fullName>19:00</fullName>
                </value>
                <value>
                    <fullName>19:30</fullName>
                </value>
                <value>
                    <fullName>20:00</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RegularTimeStart__c</fullName>
        <label>定時開始</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>7:00</fullName>
                </value>
                <value>
                    <fullName>7:30</fullName>
                </value>
                <value>
                    <fullName>8:00</fullName>
                </value>
                <value>
                    <fullName>8:30</fullName>
                </value>
                <value>
                    <fullName>9:00</fullName>
                </value>
                <value>
                    <fullName>9:30</fullName>
                </value>
                <value>
                    <fullName>10:00</fullName>
                </value>
                <value>
                    <fullName>10:30</fullName>
                </value>
                <value>
                    <fullName>11:00</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SortNumber__c</fullName>
        <label>並び順</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>関連ユーザ</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>メンバーマスタ</relationshipLabel>
        <relationshipName>MasterMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkingStatus__c</fullName>
        <label>[システム]作業状況</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>休憩中</fullName>
                </value>
                <value>
                    <fullName>外出中</fullName>
                </value>
                <value>
                    <fullName>移動中</fullName>
                </value>
                <value>
                    <fullName>作業中</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi_output_dir/objects/TimeStamp__c.object
<CustomObject>
    <label>打刻</label>
    <nameField>
        <displayFormat>打刻No{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>打刻No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AttendanceTimeSelection__c</fullName>
        <label>出勤時間(選択)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TimeList30</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DailyReportId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>関連日報</label>
        <referenceTo>DailyReport__c</referenceTo>
        <relationshipLabel>打刻</relationshipLabel>
        <relationshipName>TimeStamps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DisplayTimeStamp__c</fullName>
        <formula>MID( TEXT( CreatedDate + 0.375 ),0, 10 )
+
&quot;　&quot;
+
MID( TEXT( CreatedDate + 0.375 ), 12, 8)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>[表示用]タイムスタンプ</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeavingTimeSelection__c</fullName>
        <label>退勤時間(選択)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TimeList30Next</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MasterMemberId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>関連メンバー</label>
        <referenceTo>MasterMember__c</referenceTo>
        <relationshipLabel>打刻</relationshipLabel>
        <relationshipName>TimeStamps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TimeStampType__c</fullName>
        <label>打刻種類</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>出社打刻</fullName>
                </value>
                <value>
                    <fullName>退社打刻</fullName>
                </value>
                <value>
                    <fullName>休憩開始</fullName>
                </value>
                <value>
                    <fullName>休憩終了</fullName>
                </value>
                <value>
                    <fullName>外出</fullName>
                </value>
                <value>
                    <fullName>戻り</fullName>
                </value>
                <value>
                    <fullName>移動開始</fullName>
                </value>
                <value>
                    <fullName>移動終了</fullName>
                </value>
                <value>
                    <fullName>作業開始</fullName>
                </value>
                <value>
                    <fullName>作業終了</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi_output_dir/globalValueSets/TimeList30.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0:00</fullName>
    </customValue>
    <customValue>
        <fullName>0:30</fullName>
    </customValue>
    <customValue>
        <fullName>1:00</fullName>
    </customValue>
    <customValue>
        <fullName>1:30</fullName>
    </customValue>
    <customValue>
        <fullName>2:00</fullName>
    </customValue>
    <customValue>
        <fullName>2:30</fullName>
    </customValue>
    <customValue>
        <fullName>3:00</fullName>
    </customValue>
    <customValue>
        <fullName>3:30</fullName>
    </customValue>
    <customValue>
        <fullName>4:00</fullName>
    </customValue>
    <customValue>
        <fullName>4:30</fullName>
    </customValue>
    <customValue>
        <fullName>5:00</fullName>
    </customValue>
    <customValue>
        <fullName>5:30</fullName>
    </customValue>
    <customValue>
        <fullName>6:00</fullName>
    </customValue>
    <customValue>
        <fullName>6:30</fullName>
    </customValue>
    <customValue>
        <fullName>7:00</fullName>
    </customValue>
    <customValue>
        <fullName>7:30</fullName>
    </customValue>
    <customValue>
        <fullName>8:00</fullName>
    </customValue>
    <customValue>
        <fullName>8:30</fullName>
    </customValue>
    <customValue>
        <fullName>9:00</fullName>
    </customValue>
    <customValue>
        <fullName>9:30</fullName>
    </customValue>
    <customValue>
        <fullName>10:00</fullName>
    </customValue>
    <customValue>
        <fullName>10:30</fullName>
    </customValue>
    <customValue>
        <fullName>11:00</fullName>
    </customValue>
    <customValue>
        <fullName>11:30</fullName>
    </customValue>
    <customValue>
        <fullName>12:00</fullName>
    </customValue>
    <customValue>
        <fullName>12:30</fullName>
    </customValue>
    <customValue>
        <fullName>13:00</fullName>
    </customValue>
    <customValue>
        <fullName>13:30</fullName>
    </customValue>
    <customValue>
        <fullName>14:00</fullName>
    </customValue>
    <customValue>
        <fullName>14:30</fullName>
    </customValue>
    <masterLabel>時間入力（30分刻み）</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TimeList30Next.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0:00</fullName>
    </customValue>
    <customValue>
        <fullName>0:30</fullName>
    </customValue>
    <customValue>
        <fullName>1:00</fullName>
    </customValue>
    <customValue>
        <fullName>1:30</fullName>
    </customValue>
    <customValue>
        <fullName>2:00</fullName>
    </customValue>
    <customValue>
        <fullName>2:30</fullName>
    </customValue>
    <customValue>
        <fullName>3:00</fullName>
    </customValue>
    <customValue>
        <fullName>3:30</fullName>
    </customValue>
    <customValue>
        <fullName>4:00</fullName>
    </customValue>
    <customValue>
        <fullName>4:30</fullName>
    </customValue>
    <customValue>
        <fullName>5:00</fullName>
    </customValue>
    <customValue>
        <fullName>5:30</fullName>
    </customValue>
    <customValue>
        <fullName>6:00</fullName>
    </customValue>
    <customValue>
        <fullName>6:30</fullName>
    </customValue>
    <customValue>
        <fullName>7:00</fullName>
    </customValue>
    <customValue>
        <fullName>7:30</fullName>
    </customValue>
    <customValue>
        <fullName>8:00</fullName>
    </customValue>
    <customValue>
        <fullName>8:30</fullName>
    </customValue>
    <customValue>
        <fullName>9:00</fullName>
    </customValue>
    <customValue>
        <fullName>9:30</fullName>
    </customValue>
    <customValue>
        <fullName>10:00</fullName>
    </customValue>
    <customValue>
        <fullName>10:30</fullName>
    </customValue>
    <customValue>
        <fullName>11:00</fullName>
    </customValue>
    <customValue>
        <fullName>11:30</fullName>
    </customValue>
    <customValue>
        <fullName>12:00</fullName>
    </customValue>
    <customValue>
        <fullName>12:30</fullName>
    </customValue>
    <customValue>
        <fullName>13:00</fullName>
    </customValue>
    <customValue>
        <fullName>13:30</fullName>
    </customValue>
    <customValue>
        <fullName>14:00</fullName>
    </customValue>
    <customValue>
        <fullName>14:30</fullName>
    </customValue>
    <masterLabel>時間入力（30分刻み翌表示）</masterLabel>
</GlobalValueSet>

mdapi_output_dir/classes/Lwc_Find_Attendance_Controller.cls
public with sharing class Lwc_Find_Attendance_Controller {
    /* ------------------------------------------------
       myシリーズで使用：ログインユーザの情報
    ------------------------------------------------ */
    @AuraEnabled
    public static List<MasterMember__c> findMyMasterMember(Id UserId) {
        return [SELECT Id
                FROM MasterMember__c
                WHERE UserId__c = :UserId
                LIMIT 1
                ];
    }

    @AuraEnabled
    public static List<MasterMember__c> findMasterMember(Id MasterMemberId) {
        return [SELECT Id,Name,ArrivalStatus__c,WorkingStatus__c,Affiliation__c,UserId__c
                FROM MasterMember__c
                WHERE Id = :MasterMemberId];
    }

    @AuraEnabled
    public static List<MasterMember__c> findMasterMembers(String Affiliation) {
        if(Affiliation == 'All'){
            return [SELECT Id,Name,RegularTimeStart__c,RegularTimeEnd__c,UserId__c FROM MasterMember__c WHERE EmploymentState__c = '在職' ORDER BY SortNumber__c ASC];
        }else{
            return [SELECT Id,Name,RegularTimeStart__c,RegularTimeEnd__c,UserId__c FROM MasterMember__c WHERE EmploymentState__c = '在職' AND Affiliation__c = :Affiliation ORDER BY SortNumber__c ASC];
        }
    }

    @AuraEnabled
    public static List<DailyReport__c> findMyDailyReport(String SelectDateProcess,Id MemberId) {
        Date SelectDate = Date.valueOf(SelectDateProcess);
        return [SELECT Id,Date__c,DailyReportType__c,
                    ScheduledAttendanceTime__c,ScheduledLeavingTime__c,
                    AttendanceTime__c,LeavingTime__c,
                    AttendanceTimeSelection__c,DisplayTimeStampAttendanceTime__c,
                    LeavingTimeSelection__c,DisplayTimeStampLeavingTime__c,
                    HolidayWorkTime__c,MidnightTimeHour__c,OverTimeHour__c,ActualTime__c,BreakTimeSelection__c,
                    MasterMemberId__r.Id,MasterMemberId__r.Name
                    FROM DailyReport__c
                    WHERE Date__c = :SelectDate AND MasterMemberId__c = :MemberId];
        /*
        return [SELECT Id,HolidayWorkTime__c,MidnightTimeHour__c,OverTimeHour__c,ActualTime__c,BreakTimeSelection__c,DailyReportType__c,Date__c,MemberId__r.Id,MemberId__r.Name,AttendanceTime__c,LeavingTime__c,
                        DisplayTimeStampAttendanceTime__c,DisplayTimeStampLeavingTime__c,Week__c
                    FROM DailyReport__c
                    WHERE Date__c = :SelectDate AND MemberId__c = :MemberId];
        */
    }

    @AuraEnabled
    public static List<DailyReport__c> findDailyReport(String StartDateProcess,String EndDateProcess,Id MemberId) {
        Date StartDate = Date.valueOf(StartDateProcess);
        Date EndDate = Date.valueOf(EndDateProcess);
       return [SELECT Id,Date__c,DailyReportType__c,
                    ScheduledAttendanceTime__c,ScheduledLeavingTime__c,
                    AttendanceTime__c,LeavingTime__c,
                    AttendanceTimeSelection__c,DisplayTimeStampAttendanceTime__c,
                    LeavingTimeSelection__c,DisplayTimeStampLeavingTime__c,
                    HolidayWorkTime__c,MidnightTimeHour__c,OverTimeHour__c,ActualTime__c,BreakTimeSelection__c,
                    MasterMemberId__r.Id,MasterMemberId__r.Name
                    FROM DailyReport__c
                    WHERE Date__c >= :StartDate AND Date__c <= :EndDate AND MasterMemberId__c = :MemberId];
    }

    @AuraEnabled
    public static String upsertDailyReport(List<DailyReport__c> UpsertList) {
        upsert UpsertList DailyReport__c.Fields.Id;
        return 'OK';
    }

    @AuraEnabled
    public static List<TimeStamp__c> findTimeStamp(Id DailyReportId) {
        if(DailyReportId == null){
            return new List<TimeStamp__c>();
        }
        return [SELECT Id,CreatedDate,TimeStampType__c,DisplayTimeStamp__c FROM TimeStamp__c WHERE DailyReportId__c = :DailyReportId ORDER BY CreatedDate DESC ];
    }

    /* 行動検索 */
    @AuraEnabled
    public static List<Event> findEvent(String SelectDateProcess,Id UserID) {
        Date SelectDate = Date.valueOf(SelectDateProcess);
        return [SELECT Id,Subject,ActivityDate,Type,StartDateTime,EndDateTime,DurationInMinutes,
                    IsAllDayEvent,StartTime__c,EndTime__c
                    FROM Event
                    WHERE ActivityDate = :SelectDate AND OwnerId =:UserID
                    ORDER BY IsAllDayEvent DESC, StartDateTime ASC
        ];
    }
    
}