mdapi_output_dir/objects/DailyReport__c.object
<CustomObject>
    <label>日報</label>
    <nameField>
        <displayFormat>日報No{0000}</displayFormat>
        <label>日報No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AttendanceTimeSelection__c</fullName>
        <label>出勤時間（入力）</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TimeList30</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LeavingTimeSelection__c</fullName>
        <label>退勤時間（入力）</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TimeList30Next</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MasterMemberId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>関連メンバー</label>
        <referenceTo>MasterMember__c</referenceTo>
        <relationshipLabel>日報</relationshipLabel>
        <relationshipName>DailyReports</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapi_output_dir/objects/MasterMember__c.object
<CustomObject>
    <label>メンバーマスタ</label>
    <nameField>
        <label>名前</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>関連ユーザ</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>メンバーマスタ</relationshipLabel>
        <relationshipName>MasterMember</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapi_output_dir/objects/TimeStamp__c.object
<CustomObject>
    <label>打刻</label>
    <nameField>
        <displayFormat>打刻No{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>打刻No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AttendanceTimeSelection__c</fullName>
        <label>出勤時間(選択)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TimeList30</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CalculationTimeSelection__c</fullName>
        <label>[システム]選択時間</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>IcCard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IC打刻</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LeavingTimeSelection__c</fullName>
        <label>退勤時間(選択)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TimeList30Next</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MasterMemberId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>関連メンバー</label>
        <referenceTo>MasterMember__c</referenceTo>
        <relationshipLabel>打刻</relationshipLabel>
        <relationshipName>TimeStamps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TimeInputType__c</fullName>
        <label>[システムテスト用]時間入力種別</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TimeStampType__c</fullName>
        <label>打刻種類</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>出社打刻</fullName>
                </value>
                <value>
                    <fullName>退社打刻</fullName>
                </value>
                <value>
                    <fullName>休憩開始</fullName>
                </value>
                <value>
                    <fullName>休憩終了</fullName>
                </value>
                <value>
                    <fullName>外出</fullName>
                </value>
                <value>
                    <fullName>戻り</fullName>
                </value>
                <value>
                    <fullName>移動開始</fullName>
                </value>
                <value>
                    <fullName>移動終了</fullName>
                </value>
                <value>
                    <fullName>作業開始</fullName>
                </value>
                <value>
                    <fullName>作業終了</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi_output_dir/globalValueSets/TimeList30.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0:00</fullName>
    </customValue>
    <customValue>
        <fullName>0:30</fullName>
    </customValue>
    <customValue>
        <fullName>1:00</fullName>
    </customValue>
    <customValue>
        <fullName>1:30</fullName>
    </customValue>
    <customValue>
        <fullName>2:00</fullName>
    </customValue>
    <customValue>
        <fullName>2:30</fullName>
    </customValue>
    <customValue>
        <fullName>3:00</fullName>
    </customValue>
    <customValue>
        <fullName>3:30</fullName>
    </customValue>
    <customValue>
        <fullName>4:00</fullName>
    </customValue>
    <customValue>
        <fullName>4:30</fullName>
    </customValue>
    <customValue>
        <fullName>5:00</fullName>
    </customValue>
    <customValue>
        <fullName>5:30</fullName>
    </customValue>
    <customValue>
        <fullName>6:00</fullName>
    </customValue>
    <customValue>
        <fullName>6:30</fullName>
    </customValue>
    <customValue>
        <fullName>7:00</fullName>
    </customValue>
    <customValue>
        <fullName>7:30</fullName>
    </customValue>
    <customValue>
        <fullName>8:00</fullName>
    </customValue>
    <customValue>
        <fullName>8:30</fullName>
    </customValue>
    <customValue>
        <fullName>9:00</fullName>
    </customValue>
    <customValue>
        <fullName>9:30</fullName>
    </customValue>
    <customValue>
        <fullName>10:00</fullName>
    </customValue>
    <customValue>
        <fullName>10:30</fullName>
    </customValue>
    <customValue>
        <fullName>11:00</fullName>
    </customValue>
    <customValue>
        <fullName>11:30</fullName>
    </customValue>
    <customValue>
        <fullName>12:00</fullName>
    </customValue>
    <customValue>
        <fullName>12:30</fullName>
    </customValue>
    <customValue>
        <fullName>13:00</fullName>
    </customValue>
    <customValue>
        <fullName>13:30</fullName>
    </customValue>
    <customValue>
        <fullName>14:00</fullName>
    </customValue>
    <customValue>
        <fullName>14:30</fullName>
    </customValue>
    <customValue>
        <fullName>19:30</fullName>
    </customValue>
    <customValue>
        <fullName>22:30</fullName>
    </customValue>
    <masterLabel>時間入力（30分刻み）</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TimeList30Next.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0:00</fullName>
    </customValue>
    <customValue>
        <fullName>0:30</fullName>
    </customValue>
    <customValue>
        <fullName>1:00</fullName>
    </customValue>
    <customValue>
        <fullName>1:30</fullName>
    </customValue>
    <customValue>
        <fullName>2:00</fullName>
    </customValue>
    <customValue>
        <fullName>2:30</fullName>
    </customValue>
    <customValue>
        <fullName>3:00</fullName>
    </customValue>
    <customValue>
        <fullName>3:30</fullName>
    </customValue>
    <customValue>
        <fullName>4:00</fullName>
    </customValue>
    <customValue>
        <fullName>4:30</fullName>
    </customValue>
    <customValue>
        <fullName>5:00</fullName>
    </customValue>
    <customValue>
        <fullName>5:30</fullName>
    </customValue>
    <customValue>
        <fullName>6:00</fullName>
    </customValue>
    <customValue>
        <fullName>6:30</fullName>
    </customValue>
    <customValue>
        <fullName>7:00</fullName>
    </customValue>
    <customValue>
        <fullName>7:30</fullName>
    </customValue>
    <customValue>
        <fullName>8:00</fullName>
    </customValue>
    <customValue>
        <fullName>8:30</fullName>
    </customValue>
    <customValue>
        <fullName>9:00</fullName>
    </customValue>
    <customValue>
        <fullName>9:30</fullName>
    </customValue>
    <customValue>
        <fullName>10:00</fullName>
    </customValue>
    <customValue>
        <fullName>10:30</fullName>
    </customValue>
    <customValue>
        <fullName>11:00</fullName>
    </customValue>
    <customValue>
        <fullName>11:30</fullName>
    </customValue>
    <customValue>
        <fullName>12:00</fullName>
    </customValue>
    <customValue>
        <fullName>12:30</fullName>
    </customValue>
    <customValue>
        <fullName>13:00</fullName>
    </customValue>
    <customValue>
        <fullName>13:30</fullName>
    </customValue>
    <customValue>
        <fullName>14:00</fullName>
    </customValue>
    <customValue>
        <fullName>14:30</fullName>
    </customValue>
    <customValue>
        <fullName>19:30</fullName>
    </customValue>
    <customValue>
        <fullName>22:30</fullName>
    </customValue>
    <customValue>
        <fullName>翌2:30</fullName>
    </customValue>
    <masterLabel>時間入力（30分刻み翌表示）</masterLabel>
</GlobalValueSet>

mdapi_output_dir/classes/TimeStampAutoTest.cls
@isTest
public class TimeStampAutoTest {

    // 登録時のテスト（出社打刻）日報データあり
    @isTest static void test_create1(){
        // テストデータ作成
        // 日報データ
        DailyReport__c insDrt = CreateDailyReport();
        insert InsDrt;

        // 打刻データ
        // 現在のユーザIDを設定
        String USRID = UserInfo.getUserId();
        TimeStamp__c insEbs1 = new TimeStamp__c(
            TimeStampType__c = '出社打刻',
            AttendanceTimeSelection__c = '9:30',
            TimeInputType__c = '１５分刻み'
        );
        
        // テスト開始
        Test.startTest();
        Database.SaveResult result = Database.insert(insEbs1, false);        
        Test.stopTest();
    }

    // 登録時のテスト（出社打刻）日報データなし
    @isTest static void test_create2(){
        // 本日を設定
        Date TDY = Date.today();        
        // 退勤時間
        Datetime EndDate = Datetime.newInstance(TDY.year(), TDY.month(), TDY.day(), 23, 12, 0);

        // テストデータ作成
        // 従業員データ
        MasterMember__c insMnb = CreateMember();
        insert InsMnb;

        // 打刻データ
        // 現在のユーザIDを設定
        String USRID = UserInfo.getUserId();
        TimeStamp__c insEbs1 = new TimeStamp__c(
            TimeStampType__c = '出社打刻',
            AttendanceTimeSelection__c = '22:30',
            CalculationTimeSelection__c = EndDate,
            TimeInputType__c = '手入力'
        );
        
        // テスト開始
        Test.startTest();
        Database.SaveResult result = Database.insert(insEbs1, false);        
        Test.stopTest();
    }

    // 登録時のテスト（出社打刻）日報データあり
    @isTest static void test_create3(){
        // 本日を設定
        Date TDY = Date.today();        
        // 退勤時間
        Datetime EndDate = Datetime.newInstance(TDY.year(), TDY.month(), TDY.day(), 23, 12, 0);

        // テストデータ作成
        // 日報データ
        DailyReport__c insDrt = CreateDailyReport();
        insert InsDrt;

        // 打刻データ
        // 現在のユーザIDを設定
        String USRID = UserInfo.getUserId();
        TimeStamp__c insEbs1 = new TimeStamp__c(
            TimeStampType__c = '出社打刻',
            LeavingTimeSelection__c  = '19:30',
            CalculationTimeSelection__c = EndDate,
            TimeInputType__c = 'タイムスタンプ'
        );
        
        // テスト開始
        Test.startTest();
        Database.SaveResult result = Database.insert(insEbs1, false);
        Test.stopTest();
    }

    // 登録時のテスト（出社打刻）日報データなし
    @isTest static void test_create4(){
        // テストデータ作成
        // 従業員データ
        MasterMember__c insMnb = CreateMember();
        insert InsMnb;

        // 打刻データ
        // 現在のユーザIDを設定
        String USRID = UserInfo.getUserId();
        TimeStamp__c insEbs2 = new TimeStamp__c(
            TimeStampType__c = '出社打刻',
            IcCard__c = True,
            MasterMemberId__c = InsMnb.Id,
            LeavingTimeSelection__c  = '翌2:30',
            TimeInputType__c = '30分刻み'
        );
        
        // テスト開始
        Test.startTest();
        Database.SaveResult result = Database.insert(insEbs2, false);
        Test.stopTest();
    }

    // 登録時のテスト（出社打刻）日報データなし
    @isTest static void test_create5(){
        // テストデータ作成
        // 従業員データ
        MasterMember__c insMnb = CreateMember();
        insert InsMnb;

        // 打刻データ
        // 現在のユーザIDを設定
        String USRID = UserInfo.getUserId();
        TimeStamp__c insEbs2 = new TimeStamp__c(
            TimeStampType__c = '出社打刻',
            IcCard__c = True,
            MasterMemberId__c = InsMnb.Id,
            LeavingTimeSelection__c  = '翌2:30'
        );
        
        // テスト開始
        Test.startTest();
        Database.SaveResult result = Database.insert(insEbs2, false);
        Test.stopTest();
    }

    // 登録時のテスト（退社打刻）日報データあり
    @isTest static void test_create6(){
        // テストデータ作成
        // 日報データ
        DailyReport__c insDrt = CreateDailyReport();
        insert InsDrt;

        // 打刻データ
        // 現在のユーザIDを設定
        String USRID = UserInfo.getUserId();
        TimeStamp__c insEbs1 = new TimeStamp__c(
            TimeStampType__c = '退社打刻',
            AttendanceTimeSelection__c = '9:30',
            TimeInputType__c = '１５分刻み'
        );
        
        // テスト開始
        Test.startTest();
        Database.SaveResult result = Database.insert(insEbs1, false);        
        Test.stopTest();
    }

    // 登録時のテスト（退社打刻）日報データなし
    @isTest static void test_create7(){
        // 本日を設定
        Date TDY = Date.today();        
        // 退勤時間
        Datetime EndDate = Datetime.newInstance(TDY.year(), TDY.month(), TDY.day(), 23, 12, 0);

        // テストデータ作成
        // 従業員データ
        MasterMember__c insMnb = CreateMember();
        insert InsMnb;

        // 打刻データ
        // 現在のユーザIDを設定
        String USRID = UserInfo.getUserId();
        TimeStamp__c insEbs1 = new TimeStamp__c(
            TimeStampType__c = '退社打刻',
            AttendanceTimeSelection__c = '22:30',
            CalculationTimeSelection__c = EndDate,
            TimeInputType__c = '手入力'
        );
        
        // テスト開始
        Test.startTest();
        Database.SaveResult result = Database.insert(insEbs1, false);        
        Test.stopTest();
    }

    // 登録時のテスト（退社打刻）日報データあり
    @isTest static void test_create8(){
        // 本日を設定
        Date TDY = Date.today();        
        // 退勤時間
        Datetime EndDate = Datetime.newInstance(TDY.year(), TDY.month(), TDY.day(), 23, 12, 0);

        // テストデータ作成
        // 日報データ
        DailyReport__c insDrt = CreateDailyReport();
        insert InsDrt;

        // 打刻データ
        // 現在のユーザIDを設定
        String USRID = UserInfo.getUserId();
        TimeStamp__c insEbs1 = new TimeStamp__c(
            TimeStampType__c = '退社打刻',
            LeavingTimeSelection__c  = '19:30',
            CalculationTimeSelection__c = EndDate,
            TimeInputType__c = 'タイムスタンプ'
        );
        
        // テスト開始
        Test.startTest();
        Database.SaveResult result = Database.insert(insEbs1, false);
        Test.stopTest();
    }

    // 登録時のテスト（退社打刻）日報データなし
    @isTest static void test_create9(){
        // テストデータ作成
        // 従業員データ
        MasterMember__c insMnb = CreateMember();
        insert InsMnb;

        // 打刻データ
        // 現在のユーザIDを設定
        String USRID = UserInfo.getUserId();
        TimeStamp__c insEbs2 = new TimeStamp__c(
            TimeStampType__c = '退社打刻',
            IcCard__c = True,
            MasterMemberId__c = InsMnb.Id,
            LeavingTimeSelection__c  = '翌2:30',
            TimeInputType__c = '30分刻み'
        );
        
        // テスト開始
        Test.startTest();
        Database.SaveResult result = Database.insert(insEbs2, false);
        Test.stopTest();
    }

    // 登録時のテスト（退社打刻）日報データなし
    @isTest static void test_create10(){
        // テストデータ作成
        // 従業員データ
        MasterMember__c insMnb = CreateMember();
        insert InsMnb;

        // 打刻データ
        // 現在のユーザIDを設定
        String USRID = UserInfo.getUserId();
        TimeStamp__c insEbs2 = new TimeStamp__c(
            TimeStampType__c = '退社打刻',
            IcCard__c = True,
            MasterMemberId__c = InsMnb.Id,
            LeavingTimeSelection__c  = '翌2:30'
        );
        
        // テスト開始
        Test.startTest();
        Database.SaveResult result = Database.insert(insEbs2, false);
        Test.stopTest();
    }

    // 登録時のテスト（出社打刻、退社打刻以外）
    @isTest static void test_create11(){
        // テストデータ作成
        // 従業員データ
        MasterMember__c insMnb = CreateMember();
        insert InsMnb;

        // 打刻データ
        // 現在のユーザIDを設定
        String USRID = UserInfo.getUserId();
        TimeStamp__c insEbs1 = new TimeStamp__c(
            TimeStampType__c = '移動開始'
        );
        TimeStamp__c insEbs2 = new TimeStamp__c(
            TimeStampType__c = '移動終了'
        );
        TimeStamp__c insEbs3 = new TimeStamp__c(
            TimeStampType__c = '作業開始'
        );
        TimeStamp__c insEbs4 = new TimeStamp__c(
            TimeStampType__c = '作業終了'
        );
        TimeStamp__c insEbs5 = new TimeStamp__c(
            TimeStampType__c = '休憩開始'
        );
        TimeStamp__c insEbs6 = new TimeStamp__c(
            TimeStampType__c = '休憩終了'
        );
        TimeStamp__c insEbs7 = new TimeStamp__c(
            TimeStampType__c = '出社打刻'
        );
        TimeStamp__c insEbs8 = new TimeStamp__c(
            TimeStampType__c = '退社打刻'
        );
        TimeStamp__c insEbs9 = new TimeStamp__c(
            TimeStampType__c = '外出'
        );
        TimeStamp__c insEbs10 = new TimeStamp__c(
            TimeStampType__c = '戻り'
        );
        
        // テスト開始
        Test.startTest();
        Database.SaveResult result = Database.insert(insEbs1, false);
        result = Database.insert(insEbs2, false);
        result = Database.insert(insEbs3, false);
        result = Database.insert(insEbs4, false);
        result = Database.insert(insEbs5, false);
        result = Database.insert(insEbs6, false);
        result = Database.insert(insEbs7, false);
        result = Database.insert(insEbs8, false);
        result = Database.insert(insEbs9, false);
        result = Database.insert(insEbs10, false);
        Test.stopTest();
    }

    
    
    // 従業員テストデータ作成
    private static MasterMember__c  CreateMember(){
        // 現在のユーザIDを設定
        String USRID = UserInfo.getUserId();
        
        // データ作成
        MasterMember__c mnb = new MasterMember__c(
            Name = 'テストメンバー',
            UserId__c = USRID
        );
        return mnb;
    }

    // 日報テストデータ作成
    private static DailyReport__c   CreateDailyReport(){
        // 本日を設定
        Date TDY = Date.today();        
        // メンバーデータ作成
        MasterMember__c insMnb = CreateMember();
        insert InsMnb;
        String MNBID = InsMnb.Id;
        // 現在のユーザIDを設定
        String USRID = UserInfo.getUserId();
        
        // データ作成
        DailyReport__c drt = new DailyReport__c(
            Date__c = TDY,
            MasterMemberId__c = MNBID,
            OwnerId = USRID
        );
        return drt;
    }
}