mdapi_output_dir/objects/DailyReport__c.object
<CustomObject>
    <label>日報</label>
    <nameField>
        <displayFormat>日報No{0000}</displayFormat>
        <label>日報No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AttendanceTimeSelection__c</fullName>
        <label>出勤時間（入力）</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TimeList30</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>BreakTimeSelection__c</fullName>
        <label>休憩時間（入力）</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>0.5</fullName>
                </value>
                <value>
                    <fullName>1.0</fullName>
                    <default>true</default>
                    <label>1.0</label>
                </value>
                <value>
                    <fullName>1.5</fullName>
                </value>
                <value>
                    <fullName>2.0</fullName>
                </value>
                <value>
                    <fullName>2.5</fullName>
                </value>
                <value>
                    <fullName>3.0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BreakTime__c</fullName>
        <label>休憩時間（分）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DailyReportType__c</fullName>
        <label>日報種別</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>出勤</fullName>
                </value>
                <value>
                    <fullName>休日</fullName>
                </value>
                <value>
                    <fullName>有休</fullName>
                </value>
                <value>
                    <fullName>代休</fullName>
                </value>
                <value>
                    <fullName>欠勤</fullName>
                </value>
                <value>
                    <fullName>特休</fullName>
                </value>
                <value>
                    <fullName>休日出勤</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>日付</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LeavingTimeSelection__c</fullName>
        <label>退勤時間（入力）</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TimeList30Next</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MasterMemberId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>関連メンバー</label>
        <referenceTo>MasterMember__c</referenceTo>
        <relationshipLabel>日報</relationshipLabel>
        <relationshipName>DailyReports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MidnightTime__c</fullName>
        <label>深夜時間（分）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OverTime__c</fullName>
        <label>時間外（分）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PaidTime__c</fullName>
        <label>有休時間（分）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WorkTime__c</fullName>
        <label>労働時間（分）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

mdapi_output_dir/objects/MasterMember__c.object
<CustomObject>
    <label>メンバーマスタ</label>
    <nameField>
        <label>名前</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Affiliation__c</fullName>
        <label>所属部署</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>営業部</fullName>
                </value>
                <value>
                    <fullName>技術部</fullName>
                </value>
                <value>
                    <fullName>総務部</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EmploymentState__c</fullName>
        <label>雇用状況</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>在職</fullName>
                </value>
                <value>
                    <fullName>休職</fullName>
                </value>
                <value>
                    <fullName>退職</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>関連ユーザ</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>メンバーマスタ</relationshipLabel>
        <relationshipName>MasterMember</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapi_output_dir/objects/TimeStamp__c.object
<CustomObject>
    <label>打刻</label>
    <nameField>
        <displayFormat>打刻No{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>打刻No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AttendanceTimeSelection__c</fullName>
        <label>出勤時間(選択)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TimeList30</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LeavingTimeSelection__c</fullName>
        <label>退勤時間(選択)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TimeList30Next</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MasterMemberId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>関連メンバー</label>
        <referenceTo>MasterMember__c</referenceTo>
        <relationshipLabel>打刻</relationshipLabel>
        <relationshipName>TimeStamps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TimeStampType__c</fullName>
        <label>打刻種類</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>出社打刻</fullName>
                </value>
                <value>
                    <fullName>退社打刻</fullName>
                </value>
                <value>
                    <fullName>休憩開始</fullName>
                </value>
                <value>
                    <fullName>休憩終了</fullName>
                </value>
                <value>
                    <fullName>外出</fullName>
                </value>
                <value>
                    <fullName>戻り</fullName>
                </value>
                <value>
                    <fullName>移動開始</fullName>
                </value>
                <value>
                    <fullName>移動終了</fullName>
                </value>
                <value>
                    <fullName>作業開始</fullName>
                </value>
                <value>
                    <fullName>作業終了</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi_output_dir/globalValueSets/TimeList30.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0:00</fullName>
    </customValue>
    <customValue>
        <fullName>0:30</fullName>
    </customValue>
    <customValue>
        <fullName>1:00</fullName>
    </customValue>
    <customValue>
        <fullName>1:30</fullName>
    </customValue>
    <customValue>
        <fullName>2:00</fullName>
    </customValue>
    <customValue>
        <fullName>2:30</fullName>
    </customValue>
    <customValue>
        <fullName>3:00</fullName>
    </customValue>
    <customValue>
        <fullName>3:30</fullName>
    </customValue>
    <customValue>
        <fullName>4:00</fullName>
    </customValue>
    <customValue>
        <fullName>4:30</fullName>
    </customValue>
    <customValue>
        <fullName>5:00</fullName>
    </customValue>
    <customValue>
        <fullName>5:30</fullName>
    </customValue>
    <customValue>
        <fullName>6:00</fullName>
    </customValue>
    <customValue>
        <fullName>6:30</fullName>
    </customValue>
    <customValue>
        <fullName>7:00</fullName>
    </customValue>
    <customValue>
        <fullName>7:30</fullName>
    </customValue>
    <customValue>
        <fullName>8:00</fullName>
    </customValue>
    <customValue>
        <fullName>8:30</fullName>
    </customValue>
    <customValue>
        <fullName>9:00</fullName>
    </customValue>
    <customValue>
        <fullName>9:30</fullName>
    </customValue>
    <customValue>
        <fullName>10:00</fullName>
    </customValue>
    <customValue>
        <fullName>10:30</fullName>
    </customValue>
    <customValue>
        <fullName>11:00</fullName>
    </customValue>
    <customValue>
        <fullName>11:30</fullName>
    </customValue>
    <customValue>
        <fullName>12:00</fullName>
    </customValue>
    <customValue>
        <fullName>12:30</fullName>
    </customValue>
    <customValue>
        <fullName>13:00</fullName>
    </customValue>
    <customValue>
        <fullName>13:30</fullName>
    </customValue>
    <customValue>
        <fullName>14:00</fullName>
    </customValue>
    <customValue>
        <fullName>14:30</fullName>
    </customValue>
    <customValue>
        <fullName>23:30</fullName>
    </customValue>
    <masterLabel>時間入力（30分刻み）</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TimeList30Next.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0:00</fullName>
    </customValue>
    <customValue>
        <fullName>0:30</fullName>
    </customValue>
    <customValue>
        <fullName>1:00</fullName>
    </customValue>
    <customValue>
        <fullName>1:30</fullName>
    </customValue>
    <customValue>
        <fullName>2:00</fullName>
    </customValue>
    <customValue>
        <fullName>2:30</fullName>
    </customValue>
    <customValue>
        <fullName>3:00</fullName>
    </customValue>
    <customValue>
        <fullName>3:30</fullName>
    </customValue>
    <customValue>
        <fullName>4:00</fullName>
    </customValue>
    <customValue>
        <fullName>4:30</fullName>
    </customValue>
    <customValue>
        <fullName>5:00</fullName>
    </customValue>
    <customValue>
        <fullName>5:30</fullName>
    </customValue>
    <customValue>
        <fullName>6:00</fullName>
    </customValue>
    <customValue>
        <fullName>6:30</fullName>
    </customValue>
    <customValue>
        <fullName>7:00</fullName>
    </customValue>
    <customValue>
        <fullName>7:30</fullName>
    </customValue>
    <customValue>
        <fullName>8:00</fullName>
    </customValue>
    <customValue>
        <fullName>8:30</fullName>
    </customValue>
    <customValue>
        <fullName>9:00</fullName>
    </customValue>
    <customValue>
        <fullName>9:30</fullName>
    </customValue>
    <customValue>
        <fullName>10:00</fullName>
    </customValue>
    <customValue>
        <fullName>10:30</fullName>
    </customValue>
    <customValue>
        <fullName>11:00</fullName>
    </customValue>
    <customValue>
        <fullName>11:30</fullName>
    </customValue>
    <customValue>
        <fullName>12:00</fullName>
    </customValue>
    <customValue>
        <fullName>12:30</fullName>
    </customValue>
    <customValue>
        <fullName>13:00</fullName>
    </customValue>
    <customValue>
        <fullName>13:30</fullName>
    </customValue>
    <customValue>
        <fullName>14:00</fullName>
    </customValue>
    <customValue>
        <fullName>14:30</fullName>
    </customValue>
    <customValue>
        <fullName>23:30</fullName>
    </customValue>
    <masterLabel>時間入力（30分刻み翌表示）</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Lwc_Find_Attendance_ControllerTest.cls
@isTest
public class Lwc_Find_Attendance_ControllerTest {

    @isTest static void test_Lwc_Find_Attendance_Controller() {
        // 現在のユーザIDを設定
        String USRID = UserInfo.getUserId();

        // 本日を設定
        Date TDY11 = Date.today();
        TDY11 = TDY11 + 30;
        String SDY = String.Valueof(TDY11.year())+'-'+String.Valueof(TDY11.month())+'-'+String.Valueof(TDY11.day());
        Date TDY12 = TDY11 + 30;
        String SDY2 = String.Valueof(TDY12.year())+'-'+String.Valueof(TDY12.month())+'-'+String.Valueof(TDY12.day());

        // テストデータ作成
        // メンバーデータ
        MasterMember__c InsMnb = new MasterMember__c(
            Name = 'テストメンバー',
            EmploymentState__c = '在職',
            Affiliation__c = '技術部',
            UserId__c = USRID
        );
        insert InsMnb;
        
        // 打刻データ
        TimeStamp__c InsTsp = new TimeStamp__c(
            TimeStampType__c = '出社打刻',
            MasterMemberId__c = InsMnb.Id
        );
        insert InsTsp;

	    // 日報テストデータ(本日)
        DailyReport__c InsDrt = new DailyReport__c(
            Date__c = TDY11,
            DailyReportType__c = '出勤',
            MasterMemberId__c = InsMnb.Id,
            WorkTime__c = 600,
            BreakTime__c = 60,
            OverTime__c = 60,
			PaidTime__c  = 60,
			MidnightTime__c = 60,
            OwnerId = USRID
        );
        insert InsDrt;

        // 日報データ更新
        List<DailyReport__c> updateList = new List<DailyReport__c>();
        updateList.add(new DailyReport__c(
            Id = InsDrt.Id,
            DailyReportType__c = '出勤',
            AttendanceTimeSelection__c = '10:00',
            LeavingTimeSelection__c = '23:30',
            MasterMemberId__c = InsMnb.Id,
            BreakTimeSelection__c = '1.0')
        );

        // テスト開始        
        Test.startTest();

        Lwc_Find_Attendance_Controller.findMyMasterMember(USRID);

		Lwc_Find_Attendance_Controller.findMasterMember(InsMnb.Id);

		Lwc_Find_Attendance_Controller.findMasterMembers('技術部');

		Lwc_Find_Attendance_Controller.findMyDailyReport(SDY,InsMnb.Id);

		Lwc_Find_Attendance_Controller.findDailyReport(SDY,SDY2,InsMnb.Id);

		Lwc_Find_Attendance_Controller.upsertDailyReport(updateList);

		Lwc_Find_Attendance_Controller.findTimeStamp(InsDrt.Id);

		Lwc_Find_Attendance_Controller.findEvent(SDY,USRID);

        Test.stopTest();

    }
    
}