mdapi_output_dir/objects/MasterMember__c.object
<CustomObject>
    <label>メンバーマスタ</label>
    <nameField>
        <label>名前</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>EmploymentState__c</fullName>
        <label>雇用状況</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>在職</fullName>
                </value>
                <value>
                    <fullName>休職</fullName>
                </value>
                <value>
                    <fullName>退職</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>関連ユーザ</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>メンバーマスタ</relationshipLabel>
        <relationshipName>MasterMember</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapi_output_dir/objects/TimeStamp__c.object
<CustomObject>
    <label>打刻</label>
    <nameField>
        <displayFormat>打刻No{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>打刻No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>MasterMemberId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>関連メンバー</label>
        <referenceTo>MasterMember__c</referenceTo>
        <relationshipLabel>打刻</relationshipLabel>
        <relationshipName>TimeStamps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TimeStampType__c</fullName>
        <label>打刻種類</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>出社打刻</fullName>
                </value>
                <value>
                    <fullName>退社打刻</fullName>
                </value>
                <value>
                    <fullName>休憩開始</fullName>
                </value>
                <value>
                    <fullName>休憩終了</fullName>
                </value>
                <value>
                    <fullName>外出</fullName>
                </value>
                <value>
                    <fullName>戻り</fullName>
                </value>
                <value>
                    <fullName>移動開始</fullName>
                </value>
                <value>
                    <fullName>移動終了</fullName>
                </value>
                <value>
                    <fullName>作業開始</fullName>
                </value>
                <value>
                    <fullName>作業終了</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/attendanceStatusTest.cls
@isTest
public class attendanceStatusTest {

    @isTest static void test_attendanceStatus() {
        // 現在のユーザIDを設定
        String USRID = UserInfo.getUserId();

        // 本日を設定
        Date TDY11 = Date.today();        

        // テストデータ作成
        // メンバーデータ
        MasterMember__c InsMnb = new MasterMember__c(
            Name = 'テストメンバー',
            EmploymentState__c = '在職',
            UserId__c = USRID
        );
        insert InsMnb;
        
        // メンバーデータ
        MasterMember__c InsMnb2 = new MasterMember__c(
            Name = 'テストメンバー2',
            EmploymentState__c = '在職'
        );
        insert InsMnb2;
        
        // 打刻データ
        TimeStamp__c InsTsp2 = new TimeStamp__c(
            TimeStampType__c = '外出',
            MasterMemberId__c = InsMnb2.Id
        );
        insert InsTsp2;
                
        
        // テスト開始        
        Test.startTest();

        attendanceStatus.findMember();

        Test.stopTest();

    }
    
}